language: python
python:
    - "3.6"
install:
    - cd ..
    - git clone https://github.com/donkirkby/zero-play
    - cd shibumi-games
    - pip install pipenv
    - pipenv install --dev
script:
    - MYPYPATH=../zero-play/ mypy shibumi
    - coverage run --source=shibumi -m pytest

after_success:
    - pip install codecov
    - codecov