dist: bionic
language: python
python:
    - "3.8"
install:
    - cd ..
    - git clone https://github.com/donkirkby/zero-play
    - cd shibumi-games
    - pipenv install --dev
    - pipenv graph
script:
    - set -e
    - MYPYPATH=../zero-play/ mypy shibumi
    # Add QT_DEBUG_PLUGINS=1 before xvfb-run to debug Qt library problems.
    - xvfb-run -a coverage run --source=shibumi -m pytest

after_success:
    - pip install codecov
    - codecov