remote_theme: chrisrhymes/bulma-clean-theme
title: Shibumi Games
google_analytics: UA-4644630-2
baseurl: /shibumi-games

defaults:
  - scope:
      path: ""
    values:
      hero_image: /shibumi-games/images/index_hero.jpg
      hero_darken: true
      twitter:
        card: summary_large_image
      image: images/index_hero.jpg
